linux: sliderule_main.cpp
	g++ -Wno-write-strings sliderule_main.cpp -o ../sliderule `wx-config --cxxflags` `wx-config --libs`
osx: sliderule_main.cpp
	g++ sliderule_main.cpp -o ../sliderule.app/Contents/MacOS/sliderule `wx-config --cxxflags` `wx-config --libs`



